name: CPS
version: 1.0
api: [3.0.0]
mcpe-protocol: 431
author: iRainDrop
main: iRainDrop\CPS\Main
description: KB Modifier
commands:
  cps:
    usage: "§cUsage: /cps <on/off>"
    description: Enable/Disable your CPS Counter popup
